name: Update data.txt every hour

on:
  schedule:
    - cron: "0 * * * *" # cada hora
  workflow_dispatch: # ejecución manual opcional

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update data.txt with current time
        run: |
          echo "Last update: $(date -u)" > data.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.txt
          git commit -m "Automated update at $(date -u)" || echo "No changes to commit"
          git push
        env:
          GIT_COMMITTER_NAME: "github-actions[bot]"
          GIT_COMMITTER_EMAIL: "github-actions[bot]@users.noreply.github.com"
