name: Update data.txt every hour

on:
  schedule:
    - cron: "0 * * * *" # Cada hora
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: false

      - name: Update data.txt with current time
        run: |
          echo "Last update: $(date -u)" > data.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.txt
          git commit -m "Automated update at $(date -u)" || echo "No changes to commit"
          git branch -M main
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" main
